export const NEWS_LIST_REQUEST = 'NEWS_LIST_REQUEST';
export const NEWS_LIST_SUCCESS = 'NEWS_LIST_SUCCESS';
export const NEWS_LIST_FAIL = 'NEWS_LIST_FAIL';

export const NEWS_LIST_UPDATE_REQUEST = 'NEWS_LIST_UPDATE_REQUEST';
export const NEWS_LIST_UPDATE_SUCCESS = 'NEWS_LIST_UPDATE_SUCCESS';
export const NEWS_LIST_UPDATE_CANCEL = 'NEWS_LIST_UPDATE_CANCEL';
export const NEWS_LIST_UPDATE_FAIL = 'NEWS_LIST_UPDATE_FAIL';

export const NEWS_ITEM_REQUEST = 'NEWS_ITEM_REQUEST';
export const NEWS_ITEM_SUCCESS = 'NEWS_ITEM_SUCCESS';
export const NEWS_ITEM_FAIL = 'NEWS_ITEM_FAIL';

export const COMMENTS_LIST_REQUEST = 'COMMENTS_LIST_REQUEST';
export const COMMENTS_LIST_SUCCESS = 'COMMENTS_LIST_SUCCESS';
export const COMMENTS_LIST_FAIL = 'COMMENTS_LIST_FAIL';

export const COMMENTS_LIST_UPDATE_REQUEST = 'COMMENTS_LIST_UPDATE_REQUEST';
export const COMMENTS_LIST_UPDATE_SUCCESS = 'COMMENTS_LIST_UPDATE_SUCCESS';
export const COMMENTS_LIST_UPDATE_CANCEL = 'COMMENTS_LIST_UPDATE_CANCEL';
export const COMMENTS_LIST_UPDATE_FAIL = 'COMMENTS_LIST_UPDATE_FAIL';

export const COMMENTS_REQUEST = 'COMMENTS_REQUEST';
export const COMMENTS_SUCCESS = 'COMMENTS_SUCCESS';
export const COMMENTS_FAIL = 'COMMENTS_FAIL';

export const COMMENTS_UPDATE_REQUEST = 'COMMENTS_UPDATE_REQUEST';
export const COMMENTS_UPDATE_SUCCESS = 'COMMENTS_UPDATE_SUCCESS';
export const COMMENTS_UPDATE_CANCEL = 'COMMENTS_UPDATE_CANCEL';
export const COMMENTS_UPDATE_FAIL = 'COMMENTS_UPDATE_FAIL';
